# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-18 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190318_1610'),
    ]

    operations = [
    ]
