# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-18 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190318_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post2',
            new_name='Post',
        ),
    ]
