# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-26 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190326_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
