# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20190326_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
