# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-03 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_file_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file_id',
            new_name='fileid',
        ),
    ]
