# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-15 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.CharField(max_length=120, null=True)),
                ('s_fileid', models.CharField(max_length=120, null=True)),
                ('s_content', models.TextField(null=True)),
            ],
        ),
    ]
