# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-24 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywords',
            name='유사어검색',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='keywords',
            name='키워드검색',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
